### ISSUE TITLE
dockrails start fails to start because of docker-sync API change?

### ISSUE THREAD

**Issue by ianwalter** [gmontard/dockrails#2]
I just installed this and I get the following:

```bash
❯ dockrails start
       note:  You can also run docker-sync in the background with docker-sync --daemon
Please do no longer use "dest" in your docker-sync.yml configuration - also see https://github.com/EugenMayer/docker-sync/wiki/1.2-Upgrade-Guide#dest-has-been-removed!
```

I haven't used docker-sync before but it looks like the `docker-sync.yml` should be generated differently?

**Comment by gmontard** [comment]
Thanks @ianwalter 
I just published a new version of the Gem (0.4.0) - which is now using the latest version of docker-sync and is fixing the issue you pointed.
